# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow,QFileDialog
class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(692, 449)
        self.lineEdit = QtWidgets.QLineEdit(widget)
        self.lineEdit.setGeometry(QtCore.QRect(12, 10, 161, 20))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(widget)
        self.pushButton.setGeometry(QtCore.QRect(180, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(widget)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 261, 201))
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 89, 16))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(80, 20, 89, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(140, 20, 89, 16))
        self.radioButton_3.setObjectName("radioButton_3")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(80, 50, 71, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 50, 71, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 80, 241, 111))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(widget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 260, 261, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 10, 71, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(10, 50, 241, 121))
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.groupBox_3 = QtWidgets.QGroupBox(widget)
        self.groupBox_3.setGeometry(QtCore.QRect(280, 10, 321, 181))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 20, 89, 16))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_5.setGeometry(QtCore.QRect(100, 20, 89, 16))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_6.setGeometry(QtCore.QRect(190, 20, 61, 16))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_7.setGeometry(QtCore.QRect(250, 20, 71, 16))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_8.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_9.setGeometry(QtCore.QRect(80, 50, 61, 16))
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_10.setGeometry(QtCore.QRect(150, 50, 61, 16))
        self.radioButton_10.setObjectName("radioButton_10")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(200, 50, 71, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(10, 90, 291, 81))
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.groupBox_4 = QtWidgets.QGroupBox(widget)
        self.groupBox_4.setGeometry(QtCore.QRect(280, 190, 321, 131))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_5.setGeometry(QtCore.QRect(240, 10, 71, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(10, 40, 301, 81))
        self.plainTextEdit_4.setReadOnly(True)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.groupBox_5 = QtWidgets.QGroupBox(widget)
        self.groupBox_5.setGeometry(QtCore.QRect(280, 320, 331, 121))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_6.setGeometry(QtCore.QRect(250, 10, 71, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(20, 30, 301, 81))
        self.plainTextEdit_5.setReadOnly(True)
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")

        self.retranslateUi(widget)
        self.pushButton.clicked.connect(self.open_file_directory)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "文字识别演示程序"))
        self.pushButton.setText(_translate("widget", "打开图片"))
        self.groupBox.setTitle(_translate("widget", "通用文字识别"))
        self.radioButton.setText(_translate("widget", "普通精度"))
        self.radioButton_2.setText(_translate("widget", "高精度"))
        self.radioButton_3.setText(_translate("widget", "生僻字"))
        self.checkBox.setText(_translate("widget", "位置信息"))
        self.checkBox_2.setText(_translate("widget", "检测方向"))
        self.pushButton_2.setText(_translate("widget", "识别图片"))
        self.groupBox_2.setTitle(_translate("widget", "网络图片识别"))
        self.pushButton_3.setText(_translate("widget", "识别图片"))
        self.groupBox_3.setTitle(_translate("widget", "卡证识别"))
        self.radioButton_4.setText(_translate("widget", "身份证正面"))
        self.radioButton_5.setText(_translate("widget", "身份证背面"))
        self.radioButton_6.setText(_translate("widget", "银行卡"))
        self.radioButton_7.setText(_translate("widget", "营业执照"))
        self.radioButton_8.setText(_translate("widget", "驾驶证"))
        self.radioButton_9.setText(_translate("widget", "行驶证"))
        self.radioButton_10.setText(_translate("widget", "车牌"))
        self.pushButton_4.setText(_translate("widget", "识别图片"))
        self.groupBox_4.setTitle(_translate("widget", "表格文字识别"))
        self.pushButton_5.setText(_translate("widget", "识别图片"))
        self.groupBox_5.setTitle(_translate("widget", "通用票据识别"))
        self.pushButton_6.setText(_translate("widget", "识别图片"))

    def open_file_directory(self):
        file_path = QFileDialog.getExistingDirectory(self, caption="选取文件夹",
        directory=r'C:\Users\outao\Desktop\PYQT_learn')  # 起始路径
        # self.lineEdit.setText(file_path)
        print(file_path)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()  # 窗口初始化
    ui = Ui_widget()  # 类的实例化
    ui.setupUi(MainWindow)  # 调用first_gui的方法
    MainWindow.show()  # 展示窗口
    sys.exit(app.exec_())
